AWSTemplateFormatVersion: '2010-09-09'
Description: 'This solution consists of a lambda functions which is used to fetch
  logs from Netskope and ingest to Sumo Logic.

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Author: Sumo Logic
    Description: This solution consists of a lambda functions which is used to fetch
      logs from Netskope and ingest to Sumo Logic.
    HomePageUrl: https://github.com/SumoLogic/sumologic-netskope-collector
    Labels:
    - lambda
    - sumologic
    - atlas
    - serverless
    - Netskope
    LicenseUrl: s3://appdevstore/Netskope/v1.0.1/8cb965612283cc3fbd4c181a689210b7
    Name: sumologic-netskope-collector
    ReadmeUrl: s3://appdevstore/Netskope/v1.0.1/4cdc33b3fd722adecfc59fa46ed8cb2d
    SemanticVersion: 1.0.1
    SourceCodeUrl: https://github.com/SumoLogic/sumologic-netskope-collector
    SpdxLicenseId: Apache-2.0
Outputs:
  NetskopeFunction:
    Description: NetskopeScheduler Function ARN
    Value:
      Fn::GetAtt:
      - NetskopeFunction
      - Arn
Parameters:
  NetskopeAlertEndpoint:
    Type: String
  NetskopeEventEndpoint:
    Type: String
  SumoEndpoint:
    Type: String
  Token:
    Type: String
Resources:
  NetskopeFunction:
    Properties:
      CodeUri: s3://appdevstore/Netskope/v1.0.1/7abe6042858a97542472d56e745da05f
      Description: This function gets triggered perodically via CloudWatchEvents and
        fetches logs from Netskope and ingest to SumoLogic
      Environment:
        Variables:
          ENABLE_CONSOLE_LOG: false
          ENVIRONMENT: aws
          NETSKOPE_ALERT_ENDPOINT:
            Ref: NetskopeAlertEndpoint
          NETSKOPE_EVENT_ENDPOINT:
            Ref: NetskopeEventEndpoint
          SUMO_ENDPOINT:
            Ref: SumoEndpoint
          TOKEN:
            Ref: Token
      Events:
        ScheduleRule:
          Properties:
            Schedule: rate(5 minutes)
          Type: Schedule
      Handler: netskope.main
      MemorySize: 256
      Policies:
      - AmazonDynamoDBFullAccess
      Runtime: python3.7
      Timeout: 900
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
